baseURL = "/"
languageCode = "en-us"
title = "WORKSHOP TITLE"
description = "Materials for RSE Sheffield workshop on 'WORKSHOP TITLE'"
pygmentsUseClasses=true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[module]
  [[module.imports]]
    path = "github.com/matcornic/hugo-theme-learn"
  [[module.imports]]
    path = "github.com/dzello/reveal-hugo"
    
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "WORKSHOP TITLE"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/RSE-Sheffield/git-github-gitkraken-research"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='far fa-fw fa-copy'></i> Snippets"
url = "/snippets"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-certificate'></i> CC-BY Licence"
url = "https://creativecommons.org/licenses/by/4.0/"
weight = 40

[params]
  editURL = "https://github.com/RSE-Sheffield/git-github-gitkraken-research/edit/main/content/"
  description = "WORKSHOP TITLE"
  author = "AUTHOR NAME(S), Sheffield RSE"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "rse-learn"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[params.reveal_hugo]
 theme = "white"
 load_default_plugins = false
 plugins = [
   "reveal-js/plugin/zoom-js/zoom.js",
   "reveal-js/plugin/notes/notes.js",
 ]
